spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/testBD
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
  lifetime: 600000
server:
  port: 8080

